### ISSUE TITLE
Glass transition temp

### ISSUE THREAD

**Issue by daid** [RavinMaddHatter/UFIDS_pages#1]
I glanced over the UFIDS specs, and I noticed the glass-transition temp goes from 50C up. However, PLA has a glass-transition temp of 45C...

**Comment by RavinMaddHatter** [comment]
I think this was an oversight when we were trying to clean things up. we set Tg to the same formula as Minimum print temp.

**Comment by whosawhatsis** [comment]
Everything i've read says PLA's Tg is 60-65C. Even Polycaprolactone's Tg is listed as 60C, but Polypropylene's is listed as 0C.

I've looked up the Tg for some of the highest temperature printable materials I know of (polycarbonate at 147C and polyetherimide at 215C) and both are below 255, so making the range 0-255C should be fine. Even PEEK's Tg is listed as 143C, and PTFE at 115C. I can't find any glass transition temperatures of polymers over 255, so the 0-255C range is probably better.

**Comment by davr** [comment]
Some polymers have Tg below zero. I don't know if they'll ever end up being used in FDM printers, but if you want to make it future safe...

**Comment by RavinMaddHatter** [comment]
If the polymers with negative Tg become a relevant print media we can incorporate a patch into a future versions, but for now i think 0 to 255 will cover most of our materials of interest. The real question is how to address the change. Because this is not an essential print value i don't think it is necessary to roll a new version, however every code generated before the "patch" would have an invalid value. So we have 2 options. We can patch it now and state that Tg is bugged for all version before the patch, or we can wait until the we do a real release of the standard and roll it in then. 

edit:
I think we will hold off on patching this until we do the release version. For now use a Tg of 50 (the minimum), in the next version we will add this. but i would like to hear opinions

**Comment by whosawhatsis** [comment]
Because nothing is implemented to use that data and we're using a Release candidate version instead of an official release version, I think it's safe to push the change now and consider older codes bugged.

**Comment by RavinMaddHatter** [comment]
Do we want to make an effort to support negative Tg, or should we leave that for future implementations?

**Comment by DanLipsitt** [comment]
What are the extrusion temperatures for the examples of polymers with Tg < 0? If the spread is less than 255 we can just store Tg as an offset from print temp.

**Comment by RavinMaddHatter** [comment]
I have no experience with those materials, but there are other possible solutions as well, multiply the value by 2 and subtract, is a method recommended on G+, but i don't know if that is necessary. another option would be to add a material property that covers a 512 deg range. This is similar to the solution we decided on for Scorch temp.
 Originally we handled scorch temp the same way, but it would be easier to decode in firmware if you do it with a multiply by 2
